node {
   def version_id
   stage('Preparation') {
     checkout scm                       
     version_id = "${env.BUILD_NUMBER}"
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry("https://index.docker.io/v2/", "dockerhub") {
       def app = docker.build("rganeshsharma2489/docker-example:latest", '.').push()
     }
   }
}
